baseURL = "https://liz2020.github.io/blogs"
title = "Lihao's Blog | 立昊的博客"
googleAnalytics = "UA-183495039-1"
theme = "github-style"
copyright = "© 2019. Theme by <a href=\"https://github.com/liz2020/github-style\"><span>github-style</span></a>"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Lihao Zhu"
  description = "personal blog"
  github = "liz2020"
  email = "lihaozhu@seas.upenn.edu"
  url = "https://liz2020.github.io/me"
  utterances = "liz2020/blogs"
  avatar = "https://avatars0.githubusercontent.com/u/25622540?s=460&v=4"
  keywords = "blog, google analytics"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]